CREATE TABLE IF NOT EXISTS LIMITS (
    LIMIT_ID            BIGINT  GENERATED ALWAYS AS IDENTITY NOT NULL,
    ACCOUNT             BIGINT          NOT NULL,
    EXPENSE_CATEGORY    VARCHAR(10)     NOT NULL,
    LIMIT_SUM           DECIMAL(9,2)    NOT NULL,
    REST_LIMIT          DECIMAL(9,2)    NOT NULL,
    DATETIME            TIMESTAMP with time zone NOT NULL,
    PRIMARY KEY (LIMIT_ID)
);

CREATE TABLE IF NOT EXISTS EXPENSES (
    EXPENSES_ID         BIGINT  GENERATED ALWAYS AS IDENTITY NOT NULL,
    LIMIT_ID            BIGINT  REFERENCES LIMITS (LIMIT_ID) ON DELETE CASCADE  NOT NULL,
    ACCOUNT_TO          INTEGER NOT NULL,
    CURRENCY_SHORTNAME  VARCHAR(3)  NOT NULL,
    SUM_EXPENSE         DECIMAL(9,2)    NOT NULL,
    EXPENSE_TIME        TIMESTAMP with time zone NOT NULL,
    LIMIT_EXCEEDED      BOOLEAN NOT NULL,
    PRIMARY KEY (EXPENSES_ID)
);

CREATE TABLE IF NOT EXISTS PAIR_RATE (
    CURRENCY_PAIRS  VARCHAR(10) PRIMARY KEY NOT NULL,
    RATE            DECIMAL(9,5)    NOT NULL,
    DATETIME        VARCHAR(10)  NOT NULL
);